site_name: Evolution Suisse

theme:
  name: material
  logo: img/Logo.png
  favicon: img/favicon.png

  palette:
    primary: custom
    accent: green

  font:
    text: Urbanist 

  features:
    - navigation.sections
    - navigation.instant
    - navigation.tabs

plugins:
  - glightbox
  
markdown_extensions:
  - footnotes
  - md_in_html

  # For MathJax
  - pymdownx.arithmatex:
      generic: true

  # For buttons and image control
  - attr_list

extra_javascript:
  # For MathJax: https://squidfunk.github.io/mkdocs-material/reference/mathjax/
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

  # For sortable data tables: https://squidfunk.github.io/mkdocs-material/reference/data-tables/
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tables.js

extra_css:
  - stylesheets/extra.css

edit_uri: blob/main/docs/

repo_url: https://github.com/idec-teams/2023_Evolution_Suisse

copyright: Copyright &copy; 2023 iDEC. CC-BY-4.0 | The International Directed Evolution Competition (iDEC) is a Scottish Charitable Incorporate Organisation (SCIO), registered in Scotland, with charity number：SC050826

  
nav:
  - Overview: index.md
  - Project:
      - Background: project/background.md
      - Results: project/results.md
      - Outlook: project/Outlooks.md
      - References: project/references.md
  - Documentation:
      - Protocols: documentation/protocols.md
      - Lab Notebook: documentation/notebook.md
      - Download Report: files/report.pdf
  - Team: team.md
